# Generated by Django 3.1.3 on 2021-02-28 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0006_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='modify_data',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
