# Generated by Django 3.1.3 on 2021-02-28 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0007_auto_20210228_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='modify_data',
            new_name='modify_date',
        ),
    ]
